# Commonly impersonated Indian brands in WhatsApp/SMS phishing scams,
# with their official registrable domain for comparison.
TRUSTED_BRANDS = [
    {"name": "State Bank of India (SBI)", "domain": "sbi.co.in"},
    {"name": "Paytm", "domain": "paytm.com"},
    {"name": "PhonePe", "domain": "phonepe.com"},
    {"name": "Amazon", "domain": "amazon.in"},
    {"name": "LIC", "domain": "licindia.in"},
    {"name": "HDFC Bank", "domain": "hdfcbank.com"},
    {"name": "ICICI Bank", "domain": "icicibank.com"},
    {"name": "Axis Bank", "domain": "axisbank.com"},
    {"name": "Kotak Mahindra Bank", "domain": "kotak.com"},
    {"name": "Flipkart", "domain": "flipkart.com"},
    {"name": "India Post", "domain": "indiapost.gov.in"},
    {"name": "Airtel", "domain": "airtel.in"},
    {"name": "Jio", "domain": "jio.com"},
    {"name": "IRCTC", "domain": "irctc.co.in"},
    {"name": "Income Tax Department", "domain": "incometax.gov.in"},
    {"name": "UIDAI (Aadhaar)", "domain": "uidai.gov.in"},
    {"name": "BookMyShow", "domain": "bookmyshow.com"},
    {"name": "Google", "domain": "google.com"},
    {"name": "WhatsApp", "domain": "whatsapp.com"},
    {"name": "Netflix", "domain": "netflix.com"},
]
